stages:
  - build
  - deploy
  - clean

variables:
  CI_VOLIO_PRI_KEY: $CI_VOLIO_PRI_KEY
  VOLIO_ECR_REPOSITORY_URL: repo.volio.vn
  PROJECT: tech
  APP_NAME: frontend-jacasource
  APP_NAME_ECR: frontend-jacasource
  IMAGE_TAG: $VOLIO_ECR_REPOSITORY_URL/$PROJECT/$APP_NAME_ECR

before_script:
  - docker info
  - docker login $VOLIO_ECR_REPOSITORY_URL -u $VOLIO_REPO_PUSHER -p $VOLIO_REPO_PUSHER_PWD

build:
  stage: build
  allow_failure: false
  script:
    - echo "Building image."
    - docker pull $IMAGE_TAG || echo "Building runtime from scratch"
    - >
      docker build
      --cache-from $IMAGE_TAG
      -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

clean:
  stage: clean
  allow_failure: false
  script:
    - docker image prune -f
