stages:
  - build
  - deploy
  - clean

variables:
  CI_VOLIO_PRI_KEY: $CI_VOLIO_PRI_KEY
  VOLIO_ECR_REPOSITORY_URL: repo.volio.vn
  PROJECT: tech
  APP_NAME: volio-frontend-jacasource
  APP_NAME_ECR: volio-frontend-jacasource
  IMAGE_TAG: $VOLIO_ECR_REPOSITORY_URL/$PROJECT/$APP_NAME_ECR

before_script:
  - docker login $VOLIO_ECR_REPOSITORY_URL -u $VOLIO_REPO_PUSHER -p $VOLIO_REPO_PUSHER_PWD
  - VERSION=v$(date +%Y.%b.%d)-$CI_COMMIT_SHORT_SHA

build:
  stage: build
  allow_failure: false
  script:
    - echo "Building image."
    - docker pull $IMAGE_TAG_RAW || echo "Building runtime from scratch"
    - echo $IMAGE_TAG_RAW:$VERSION
    - >
      docker build
      --cache-from $IMAGE_TAG_RAW
      -t $IMAGE_TAG_RAW:$VERSION .
    - docker push $IMAGE_TAG_RAW:$VERSION

clean:
  stage: clean
  allow_failure: false
  script:
    - docker image prune -f
    - docker container prune -f

.deploy_template:
  stage: deploy
  image: pstauffer/curl
  script:
    - echo $GITLAB_USER_NAME
    - echo $CI_COMMIT_MESSAGE
    - |
        if [ "$DEPLOY_BRANCH" = "production" ]; then
            APP_IMAGE_TAG=$VERSION
        fi

        if [ "$DEPLOY_BRANCH" = "master" ]; then
            APP_IMAGE_TAG=$VERSION
        fi
    - >
      curl -G -v --compressed -sS
      --data-urlencode "user=${GITLAB_USER_NAME}"
      --data-urlencode "commit_message=${CI_COMMIT_MESSAGE}"
      -H 'Connection: keep-alive'
      "${WEBHOOK_URL}?application=${APP_NAME}&branch=${DEPLOY_BRANCH}&commit=${CI_COMMIT_SHA}&version=${VALUES_VERSION}&app_branch=${APP_IMAGE_TAG}"
      &> /dev/stdout | tee -a /tmp/status
    - grep -q "Patching done!" /tmp/status; [ $? -eq 0 ] && exit 0 || exit 1

deploy_dev:
  extends: .deploy_template
  environment:
    name: development
  variables:
    DEPLOY_BRANCH: develop
    APP_IMAGE_TAG: dev
    WEBHOOK_URL: https://webhook.volio.vn/deploy
    VALUES_VERSION: v1.0
  only:
    - develop
    - /^dev-.*$/
    - /^feature\/.*$/
    - /^hotfix\/.*$/

deploy_staging:
  extends: .deploy_template
  environment:
    name: staging
  variables:
    DEPLOY_BRANCH: staging
    APP_IMAGE_TAG: staging
    WEBHOOK_URL: https://webhook.volio.vn/deploy
    VALUES_VERSION: v1.0
  only:
    - staging
    - /^staging-/

deploy_production:
  extends: .deploy_template
  environment:
    name: master
  variables:
    DEPLOY_BRANCH: master
    APP_IMAGE_TAG: master
    WEBHOOK_URL: https://webhook.volio.vn/deploy
    VALUES_VERSION: v1.0
  only:
    # - tags && master
    - master
